### ISSUE TITLE
Bower Update

### ISSUE THREAD

**Issue by smithandweb** [Stuk/jszip#180]
Any chance you could update your bower repo? It's still at v2.0.0. Thanks!

**Comment by xaka** [comment]
The problem is bower package is owned by different person (https://github.com/ravenac95/jszip-bower) and I've raised an issue https://github.com/ravenac95/jszip-bower/issues/2 to transfer package name to this project. If there is no response within a week, we should go to https://github.com/bower/registry/issues to resolve a dispute.

cc @Stuk

**Comment by xaka** [comment]
OK. The previous bower package has been unregistered. Thanks to @ravenac95 for prompt response. Maintainers, please register this one by doing `bower register jszip git://github.com/Stuk/jszip.zip`.

cc @Stuk @SheetJSDev @dduponchel

**Comment by xaka** [comment]
Oh, as it turned out I could do it by myself :) Hopefully it'll work and pick future releases as expected.

**Comment by Stuk** [comment]
Thanks @xaka! Can this issue now be closed?

**Comment by xaka** [comment]
For sure! Works for me.

**Comment by Stuk** [comment]
Great :)
