### ISSUE TITLE
Deterministic writes

### ISSUE THREAD

**Issue by SheetJSDev** [Stuk/jszip#183]
Given a script that builds the zip from scratch what options need to be provided to the various functions to force a deterministic write?  As a small test case in nodejs:

```
$ cat t.js
var JSZip = require('jszip');
var zip = new JSZip();
zip.file("foo", "bar baz qux");
require('fs').writeFileSync(process.argv[2], zip.generate({type:"nodebuffer"}));
$ node t.js 1.zip
$ node t.js 2.zip
$ md5 1.zip 2.zip
MD5 (1.zip) = f1a8b5917382815a38a855de5753c58a
MD5 (2.zip) = 57172d64c410d995abaf27cc6365ada2
```

**Comment by edi9999** [comment]
I have just tried to do what is said by @SheetJSDev and it doesn't seem to behave like this for me:
```
➜    node t.js 1.zip                                                                                                               
➜    node t.js 2.zip                                                                                                               
➜    md5sum 1.zip 2.zip                                                                                                            
39c0152e92b074a93926cf547e9de8ee  1.zip
39c0152e92b074a93926cf547e9de8ee  2.zip
```

**Comment by oising** [comment]
I'm having problems that may not be entirely unrelated. I'm modifying excel files (xlsx, which are zip archives) using background async promises - not sure if that really matters - and under load, the zips are getting corrupted but not in terms of the zip container, but rather entries in the zip itself. I'm seeing cases where random files within the zip are being truncated to 0 bytes. These files are not necessarily the ones I am modifying either. I am trying to isolate a reliable repro.

**Comment by kstewart83** [comment]
For anyone coming across this problem, this can happen when creating nested files in a folder structure. By default, JSZip creates intermediate folders, but will use the current date make the overall zip non-deterministic. In order to prevent this, either create the intermediate folders explicitly and set the date, or use the [createFolder](https://stuk.github.io/jszip/documentation/api_jszip/file_data.html#createfolders-option) set to false to prevent JSzip from creating the folders automatically.
