### ISSUE TITLE
Folder file entries do not have 'dir' set to true?

### ISSUE THREAD

**Issue by chrisrickard** [Stuk/jszip#198]
Hi, 

When I download and iterate the fileEntries in this zip --> https://dl.dropboxusercontent.com/u/3120684/folder.zip - It seems to be trating folders as files?

E.g, neither entry.dir or entry.options.dir are 'true' for the internal folder.

I am trying to extract the contents exactly as it appears in the zip (keeping the folder structure), any advice?

Cheers,

Chris.

**Comment by dduponchel** [comment]
When parsing a zip file, JSZip only reads the DOS attribute to know if it's a folder (see [here](https://github.com/Stuk/jszip/blob/v2.4.0/lib/zipEntry.js#L157)). This file has no DOS flags, only UNIX ones (in this zip file, a folder entry has the external file attributes `41FD4000`, meaning "folder, rights 775").
This will be fixed with #194. Maybe looking for trailing '/' too will harden this.

You can't easily fix this without modifying the JSZip code, but in the meantime you can check if the file name ends with a slash instead of checking entry.dir.

**Comment by chrisrickard** [comment]
Ok great, the slash-check will be fine for now (as I am in control of my zip contents). Thanks for the reply @dduponchel.
