### ISSUE TITLE
JSZip not working on safari 

### ISSUE THREAD

**Issue by FadySamirSadek** [Stuk/jszip#239]
i just tested the main sample you put on your main website using safari and osx 10.10 yosemitie and it is not working it seems like the blob object is not supported

**Comment by frumbert** [comment]
Seems to have already been mentioned - https://github.com/Stuk/jszip/issues/153 and https://github.com/Stuk/jszip/issues/231 - Safari for me seems like a non-usable browser for many things related to Blobs and typed arrays and local storage and so on. JSZip isn't at fault as such I don't think since other similar libraries that deal in blobs also have difficulty. I've considered tackling it myself but realised the amount of hacky nonsense I was going through outweighed the benefits. Telling people to use another browser has been enough.
