### ISSUE TITLE
.crx

### ISSUE THREAD

**Issue by galeksandrp** [Stuk/jszip#265]
I hear that .crx (chrome extensions) are zip files. And 7-zip says they are zip by Info->Properties button. But https://stuk.github.io/jszip/documentation/examples/read-local-file-api.html don't show listing of archive, and `JSZip(data).files` shows `{}`. Example of that file is https://www.eff.org/files/https-everywhere-chrome-2016.2.23.crx

**Comment by dduponchel** [comment]
A [crx file](https://developer.chrome.com/extensions/crx) is a crx package header and a zip file appended. A zip file references its own parts with offsets from the start of the file. Here, bytes are added at the beginning, all offsets are false (since the goal here is to sign a zip file, the offsets can't be updated).
While some tools detect the offset and handle it, JSZip don't (yet). We also forgot to check that case so you don't get an error... just an empty file.
I'll work on a fix.
