### ISSUE TITLE
Can't resolve 'stream'

### ISSUE THREAD

**Issue by zizizi17** [Stuk/jszip#524]
Hello. After updating the version of Angular to 6.0 I got the next error. 
```ERROR in ./node_modules/jszip/lib/readable-stream-browser.js
Module not found: Error: Can't resolve 'stream' 
Did anyone have the same?

**Comment by jmandreslopez** [comment]
I resolved that issue by adding the library to the **tsconfig.ts** like this:

```
{
  ...
  "compilerOptions": {
    ...
    "paths": {
      "jszip": [
        "../node_modules/jszip/dist/jszip.min.js"
      ]
    }
  }
}
```

**Comment by dinony** [comment]
I think that [`stream`](https://github.com/Stuk/jszip/blob/master/lib/readable-stream-browser.js) is required but not specified as a [dependency](https://github.com/Stuk/jszip/blob/master/package.json). 
Somehow, I think that `readable-stream` is used instead of `stream` when building via grunt, but other build processes do not have that mapping.

I think it's better to:

```
{
  ...
  "compilerOptions": {
    ...
    "paths": {
      "stream": ["../node_modules/readable-stream/readable.js"]
    }
  }
}
```

**Comment by christophechevalier** [comment]
@jmandreslopez No working for me.
@dinony Works fine with readable-stream.

**Comment by christophechevalier** [comment]
Hi all ! 
Some news .. :mag: 
This issue is related to angular/cli : https://github.com/angular/angular-cli/issues/9827#issuecomment-369546113
This solution solve this error : https://stackoverflow.com/a/50377270/2398593

**Comment by mo-norant** [comment]
Thanks @jmandreslopez  I did work

**Comment by davidgiven** [comment]
See also #477 which might be the same issue --- tl;dr: probably not an issue, just a misleading cosmetic warning.
