### ISSUE TITLE
Profanity in jszip.js and utils.js

### ISSUE THREAD

**Issue by adamfarley** [Stuk/jszip#570]
These files contain profanity.

Simple fix, PR ready.

https://github.com/Stuk/jszip/pull/571

**Comment by timothy-mcroy** [comment]
Why is this change needed? Or specifically, how does this improve the codebase? Since when is profanity inherently bad in source code or comments?

There's a counter argument to why profanity should remain in a codebase - Empathy. Swearing reminds you that the author wasn't the stuffy PM that made the requirements or the crabby customer. It was a human developer, with constraints and emotions and a real life background. 

Whose sheltered ears and eyes are you expecting to read this code? If a kid can't say "Fuck" but they're contributing to open source, do you honestly expect the entire Open Source community to make way for that? That kid will find all sorts of inappropriate content out on the Wild Wild Web. I've heard there are even naked people. Doing naked things. To and with other naked people. The argument you made in the JDK about it being unprofessional is merely a symptom of your prolonged exposure to IBM; it's very similar to Azkaban in that regard.

Code is not business communication. It may communicate business logic to a computer and to other developers, but there's nothing inherently good about this change. It's not making the software better, but simply meeting some arbitrary definition today of "bad word". 

Nobody is reading their code to their evangelical grandmother who might literally die of "oh-dear" overdose upon reception of a single foul word. Blood, sweat, and tears go into source code creation; people giving back to a community. Just because IBM requires that you burn your fingerprints, erase any distinguishing features about yourself, and always talk as if a customer is listening does not mean that the rest of the world has to follow **suit**

If you really want to get rid of those swear words, why not make a pull request that actually improves the content of the comments? Because rewording "well fuck" to "Calamity" just shows off that some british dude worked on this, but it's not any more informative. Instead of renaming the cussing to "TODO", why don't you actually DO THE THING you are writing TODO? A substantive improvement to the software is slightly harder than CTRL-Shift-F, but you didn't opt to do that, presumably because the goal is to establish that cussing doesn't belong in source control. 

Removing swear words for the sake of removing swear words is not a noble cause. Improve the software.

**Comment by stuart-marks** [comment]
There are several issues going on here.

1) The changes don't belong in dist/jszip.js, as that appears to be a generated file. The origin of the comments in question are lib/utf8.js and lib/utils.js. (I'm not sure why the comment from utf8.js appears twice in jszip.js. Possibly a generation error? I haven't managed to track that down.)

2) The code in utf8.js is attempting to find the first byte of a multi-byte sequence by stepping backward as long as it sees a continuation byte. If it runs off the front of the buffer, it means the UTF-8 sequence is malformed. "TODO" is misplaced here, as there's really nothing the code can do to improve or mitigate this situation. It's not clear to me that it's a fuckup either; possibly somebody has fucked up, or maybe there was data corruption somewhere. The comment also claims that the sequence is very small, which is an unwarranted assumption. The sequence might be arbitrarily large, but malformed. In any case it might be appropriate simply for the comment to say that the sequence is malformed and be done with it.

3) The utils.js code is attempting to create a Blob by looking for one of several Blob builders. Being unable to find a builder is indeed a dire circumstance, perhaps even a calamity, warranting an expletive. Which one, of course, is a matter of taste. Might I suggest something similarly evocative, such as "Oh, snap!" ?

**Comment by kyz** [comment]
What would your response be, if the community's position were of the same nature as expressed in *Arkell v. Pressdram*

**Comment by elygre** [comment]
I'm not the "you" in the comment by @kyz above, but I would be somewhat perplexed.

Actually, I already am.

I can swear ~with the best of them~ reasonably well, in multiple languages. And I often do. But when someone objects, I don't actually teach them about free speech and shit. Instead, I relax my language and see if we have anything else in common. Maybe we can coexist even without swearing?

(We sometimes can't, but I don't feel this conversation has gotten there yet.)

**Comment by timothy-mcroy** [comment]
@elygre There's a wide difference between swearing at someone and swearing at something.

The code in question swears at _something_, not someone. Nobody is being hurt by it. 

The reply in question mentioned by Kyz is hurtful, regardless of the court's decision on the libel case.

**Comment by tulssinep** [comment]
Next thing you know he is asking for politically incorrect contributors to get their requests denied because we shouldn't judge people based on their code but rather based on their political views lmao

This is happening to the linux project btw. please don't let SJW's take over programming

**Comment by timothy-mcroy** [comment]
There's a huge difference between politcal correctness and just cussing. Don't conflate the two things just because you need a safe space to be racist.

**Comment by adamfarley** [comment]
My position is that professional code should have polite comments.

Closing this issue due to the overwhelmingly negative response to a minor change.

You folks do what you want.
