### ISSUE TITLE
JSZip is 50x slower because of set-immediate-shim

### ISSUE THREAD

**Issue by ingun37** [Stuk/jszip#750]
JSZip is significantly slow in NextJS by more than 50 times compared to other platform like Gatsby.
The reason is that there's no polyfill for *setImmediate* in NextJS therefore it falls back to *set-immediate-shim* which is a very slow library.

There already has been many pull requests/issues addressing the same problem.

Stuk/jszip#702
Stuk/jszip#716
Stuk/jszip#619
https://github.com/vercel/next.js/issues/22372#issuecomment-783330758

I think this long overdue issue has to be resolved once and for all.

**Comment by 101arrowz** [comment]
It would probably be better to delegate operations to a separate thread instead of using `setImmediate` to let it run in the event loop. Even if JSZip doesn't *freeze* the browser, it still causes sluggish operation because it's crunching numbers on the main thread. Worker threads are the approach used by [fflate](https://github.com/101arrowz/fflate), which is multiple times faster.

**Comment by AnzhiZhang** [comment]
Just a kind reminder that please solve this issue, it makes it difficult for me to use this library in vercel
